id: ???
num_envs: 4
frame_stack: 1
sync_env: False
screen_size: 64
action_repeat: 1
grayscale: False
clip_rewards: False
capture_video: False
frame_stack_dilation: 1
actions_as_observation:
  num_stack: 65
  noop: 0.0
  dilation: 2
max_episode_steps: null
reward_as_observation: False
wrapper: ???
