defaults:
  - default
  - _self_

# Override from `default` config
id: TNMRGradEnv
max_episode_steps: 2000
num_envs: 1
action_repeat: 1
capture_video: False
actions_as_observation:
  num_stack: 80
  noop: 0.0
  dilation: 2


# Wrapper to be instantiated
wrapper:
  #_target_: sheeprl.utils.env.get_dummy_env
  _target_: sheeprl.envs.tnmr.TNMRGradEnv
  #_target_: gymnasium.make
  id: ${env.id}