defaults:
  - dreamer_v3_XL
  - _self_

dense_units: 64
mlp_layers: 2
world_model:
  encoder:
    cnn_channels_multiplier: 24
  recurrent_model:
    recurrent_state_size: 64
  transition_model:
    hidden_size: 128
  representation_model:
    hidden_size: 128